adwords_api/examples/adwords_on_rails/config/routes.rb
AdwordsOnRails::Application.routes.draw do
  get "home/index"

  get "campaign/index"

  get "account/index"
  get "account/input"
  get "account/select"

  get "login/prompt"
  get "login/callback"
  get "login/logout"

  get "report/index"
  post "report/get"

  root :to => "home#index"
end

adwords_api/examples/adwords_on_rails/app/models/report.rb
class Report

  REPORT_LIST = {
    'ACCOUNT_PERFORMANCE_REPORT' => {
      :name => 'Account Performance'
    },
    'ACCOUNT_REACH_FREQUENCY_REPORT' => {
      :name => 'Account Reach Frequency'
    },
    'ADGROUP_PERFORMANCE_REPORT' => {
      :name => 'Adgroup Performance'
    },
    'ADGROUP_REACH_FREQUENCY_REPORT' => {
      :name => 'Adgroup Reach Frequency'
    },
    'AD_EXTENSIONS_PERFORMANCE_REPORT' => {
      :name => 'Ad Extensions Performance'
    },
    'AD_PERFORMANCE_REPORT' => {
      :name => 'Ad Performance'
    },
    'AGE_RANGE_PERFORMANCE_REPORT' => {
      :name => 'Age Range Performance'
    },
    'AUDIENCE_PERFORMANCE_REPORT' => {
      :name => 'Audience Performance'
    },
    'AUTOMATIC_PLACEMENTS_PERFORMANCE_REPORT' => {
      :name => 'Automatic Placements Performance'
    },
    'BUDGET_PERFORMANCE_REPORT' => {
      :name => 'Budget Performance'
    },
    'CAMPAIGN_AD_SCHEDULE_TARGET_REPORT' => {
      :name => 'Campaign Ad Schedule Target'
    },
    'CAMPAIGN_LOCATION_TARGET_REPORT' => {
      :name => 'Campaign Location Target'
    },
    'CAMPAIGN_NEGATIVE_KEYWORDS_PERFORMANCE_REPORT' => {
      :name => 'Campaign Negative Keywords Performance'
    },
    'CAMPAIGN_NEGATIVE_LOCATIONS_REPORT' => {
      :name => 'Campaign Negative Locations'
    },
    'CAMPAIGN_NEGATIVE_PLACEMENTS_PERFORMANCE_REPORT' => {
      :name => 'Campaign Negative Placements Performance'
    },
    'CAMPAIGN_PERFORMANCE_REPORT' => {
      :name => 'Campaign Performance'
    },
    'CAMPAIGN_PLATFORM_TARGET_REPORT' => {
      :name => 'Campaign Platform Target'
    },
    'CAMPAIGN_REACH_FREQUENCY_REPORT' => {
      :name => 'Campaign Reach Frequency'
    },
    'CLICK_PERFORMANCE_REPORT' => {
      :name => 'Click Performance'
    },
    'CREATIVE_CONVERSION_REPORT' => {
      :name => 'Creative Conversion'
    },
    'CRITERIA_PERFORMANCE_REPORT' => {
      :name => 'Criteria Performance'
    },
    'DESTINATION_URL_REPORT' => {
      :name => 'Destination URL'
    },
    'DISPLAY_KEYWORD_PERFORMANCE_REPORT' => {
      :name => 'Display Keyword Performance'
    },
    'DISPLAY_TOPICS_PERFORMANCE_REPORT' => {
      :name => 'Display Topics Performance'
    },
    'GENDER_PERFORMANCE_REPORT' => {
      :name => 'Gender Performance'
    },
    'GEO_PERFORMANCE_REPORT' => {
      :name => 'Geo Performance'
    },
    'KEYWORDLESS_CATEGORY_REPORT' => {
      :name => 'Keywordless Category'
    },
    'KEYWORDLESS_QUERY_REPORT' => {
      :name => 'Keywordless Query'
    },
    'KEYWORDS_PERFORMANCE_REPORT' => {
      :name => 'Keywords Performance'
    },
    'PLACEHOLDER_FEED_ITEM_REPORT' => {
      :name => 'Placeholder Feed Item'
    },
    'PLACEMENT_PERFORMANCE_REPORT' => {
      :name => 'Placement Performance'
    },
    'SEARCH_QUERY_PERFORMANCE_REPORT' => {
      :name => 'Search Query Performance'
    },
    'URL_PERFORMANCE_REPORT' => {
      :name => 'URL Performance'
    }
  }

  attr_reader :id, :name

  def initialize(id, name)
    @id, @name = id, name
  end

  def self.report_for_type(report_type)
    return reports()[report_type]
  end

  def self.reports()
    @@reports ||= REPORT_LIST.inject({}) do |result, (key, value)|
      result[key] = Report.new(key, value[:name])
      result
    end
    return @@reports
  end

  def self.create_definition(template, data)
    result = template.dup()
    result[:selector][:fields] = string_to_array(data['fields'])
    result[:report_type] = data[:type]
    result[:download_format] = data[:format]
    return result
  end

  private

  def self.string_to_array(str)
    return [] if str.nil? or str.empty?
    result = str.split(',')
    return result.map {|item| item.strip}
  end
end

adwords_api/examples/adwords_on_rails/app/controllers/report_controller.rb
# See this document for reference:
#   https://developers.google.com/adwords/api/docs/appendix/reports

class ReportController < ApplicationController

  REPORT_DEFINITION_TEMPLATE = {
    :selector => {
      :fields => []
    },
    :report_name => 'AdWords on Rails report',
    :report_type => nil,
    :download_format => nil,
    :date_range_type => 'LAST_7_DAYS'
  }

  def index
    @selected_account = selected_account
    @reports = Report.reports()
    @formats = ReportFormat.report_formats()
  end

  def get
    @selected_account = selected_account
    return if @selected_account.nil?

    validate_data(params)

    api = get_adwords_api()
    report_utils = api.report_utils()
    definition = Report.create_definition(REPORT_DEFINITION_TEMPLATE, params)
    api.include_zero_impressions = true if 'true'.eql?(params[:zeroes])
    begin
      # Here we only expect reports that fit into memory. For large reports
      # you may want to save them to files and serve separately.
      report_data = report_utils.download_report(definition)
      format = ReportFormat.report_format_for_type(params[:format])
      content_type = format.content_type
      filename = format.file_name(params[:type])
      send_data(report_data, {:filename => filename, :type => content_type})
    rescue AdwordsApi::Errors::ReportError => e
      @error = e.message
    end
  end

  private

  def validate_data(data)
    format = ReportFormat.report_format_for_type(data[:format])
    raise StandardError, 'Unknown format' if format.nil?
    report = Report.report_for_type(data[:type])
    raise StandardError, 'Unknown report type' if report.nil?
  end
end

adwords_api/examples/adwords_on_rails/app/views/report/get.html.erb
<% if @error %>
  <div class="notice">
  An error occurred during report retrieval:<br><%= @error %>
  </div>
<% else %>
  <%= @report_data %>
<% end %>

<div id="local-footer">
  <span class="small-print"><a href="#" onClick="history.back();">Back</a></span>
</div>

adwords_api/examples/adwords_on_rails/app/views/report/index.html.erb
<h1>Retrieve a report</h1>

<% if @selected_account.nil? %>
  <div class="notice">No account selected!</div>

<% else %>
  See <a href="https://developers.google.com/adwords/api/docs/appendix/reports">
  reporting documentation</a> for reports and fields reference. The report will
  be ran for the last 7 days.<br>

  <% if @reports.empty? %>
    <ul><li>No reports available.</ul>
  <% else %>
    <div class="report-form">
    <%= form_tag('/report/get', :method => 'post') do %>
      <div class="report-form-item">
        Report: <select name="type">
        <% @reports.each_pair do |key, report| %>
          <option value="<%= key %>"><%= report.name %>
        <% end %>
        </select>
      </div>
      <div class="report-form-item">
      Fields: <input name="fields" value="ExternalCustomerId, AccountDescriptiveName" size="80">
      </div>
      <div class="report-form-item">
        Format: <select name="format">
          <% @formats.each_pair do |key, format| %>
          <option value="<%= key %>"><%= format.name %>
          <% end %>
        </select>
      </div>
      <div class="report-form-item">
      <input type="checkbox" name="zeroes" value="true">
      Include zero impressions
      </div>
      <div class="report-form-item">
      <input type="submit" value="Get report">
      </div>
    <% end %>
    </div>
  <% end %>

<% end %>

<div id="local-footer">
  <span class="small-print"><%= link_to("Back to home", home_index_path) %></span>
</div>